// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type RefreshToken struct {
	RefreshTokenID uuid.UUID  `json:"refresh_token_id"`
	TokenHash      string     `json:"token_hash"`
	UserID         uuid.UUID  `json:"user_id"`
	IssuedAt       time.Time  `json:"issued_at"`
	ExpiresAt      time.Time  `json:"expires_at"`
	Revoked        bool       `json:"revoked"`
	RevokedAt      *time.Time `json:"revoked_at"`
}

type User struct {
	UserID       uuid.UUID  `json:"user_id"`
	UserName     string     `json:"user_name"`
	Name         string     `json:"name"`
	Email        string     `json:"email"`
	PasswordHash string     `json:"password_hash"`
	CreatedAt    time.Time  `json:"created_at"`
	UpdatedAt    time.Time  `json:"updated_at"`
	DeletedAt    *time.Time `json:"deleted_at"`
}
