// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	CountUsers(ctx context.Context, arg CountUsersParams) (int64, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	FindUserByID(ctx context.Context, arg FindUserByIDParams) (FindUserByIDRow, error)
	GetByEmail(ctx context.Context, arg GetByEmailParams) (GetByEmailRow, error)
	HardDeleteUser(ctx context.Context, arg HardDeleteUserParams) (int64, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error)
	ResetPassword(ctx context.Context, arg ResetPasswordParams) (ResetPasswordRow, error)
	RestoreUser(ctx context.Context, arg RestoreUserParams) (RestoreUserRow, error)
	SoftDeleteUser(ctx context.Context, arg SoftDeleteUserParams) (int64, error)
	UpdateUserByID(ctx context.Context, arg UpdateUserByIDParams) (UpdateUserByIDRow, error)
}

var _ Querier = (*Queries)(nil)
