// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_token.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (
    token_hash,
    user_id,
    expires_at
) VALUES (
    $1, $2, $3
)
RETURNING 
    refresh_token_id, expires_at
`

type CreateRefreshTokenParams struct {
	TokenHash string    `json:"token_hash"`
	UserID    uuid.UUID `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
}

type CreateRefreshTokenRow struct {
	RefreshTokenID uuid.UUID `json:"refresh_token_id"`
	ExpiresAt      time.Time `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (CreateRefreshTokenRow, error) {
	row := q.db.QueryRow(ctx, createRefreshToken, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	var i CreateRefreshTokenRow
	err := row.Scan(&i.RefreshTokenID, &i.ExpiresAt)
	return i, err
}

const deleteRefreshTokenById = `-- name: DeleteRefreshTokenById :execrows
DELETE FROM refresh_tokens
WHERE token_hash = $1
`

type DeleteRefreshTokenByIdParams struct {
	TokenHash string `json:"token_hash"`
}

func (q *Queries) DeleteRefreshTokenById(ctx context.Context, arg DeleteRefreshTokenByIdParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRefreshTokenById, arg.TokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
