// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
WHERE
    deleted_at IS NULL
    AND (
        $1::text IS NULL OR 
        $1::text = '' OR
        user_name ILIKE '%' || $1 || '%' OR
        email ILIKE '%' || $1 || '%' OR
        name ILIKE '%' || $1 || '%'
    )
`

type CountUsersParams struct {
	Search *string `json:"search"`
}

func (q *Queries) CountUsers(ctx context.Context, arg CountUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users(
    user_name,
    name,
    email,
    password_hash
) VALUES (
    $1, $2, $3, $4
) RETURNING user_id, user_name, email, name
`

type CreateUserParams struct {
	UserName     string `json:"user_name"`
	Name         string `json:"name"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

type CreateUserRow struct {
	UserID   uuid.UUID `json:"user_id"`
	UserName string    `json:"user_name"`
	Email    string    `json:"email"`
	Name     string    `json:"name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.UserName,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.UserID,
		&i.UserName,
		&i.Email,
		&i.Name,
	)
	return i, err
}

const findUserByID = `-- name: FindUserByID :one
SELECT user_id, user_name, email, name
FROM users
WHERE user_id = $1 AND deleted_at IS NULL
`

type FindUserByIDParams struct {
	UserID uuid.UUID `json:"user_id"`
}

type FindUserByIDRow struct {
	UserID   uuid.UUID `json:"user_id"`
	UserName string    `json:"user_name"`
	Email    string    `json:"email"`
	Name     string    `json:"name"`
}

func (q *Queries) FindUserByID(ctx context.Context, arg FindUserByIDParams) (FindUserByIDRow, error) {
	row := q.db.QueryRow(ctx, findUserByID, arg.UserID)
	var i FindUserByIDRow
	err := row.Scan(
		&i.UserID,
		&i.UserName,
		&i.Email,
		&i.Name,
	)
	return i, err
}

const getByEmail = `-- name: GetByEmail :one
SELECT user_id, user_name, name, email, password_hash
FROM users 
WHERE EMAIL = $1 and deleted_at IS NULL
`

type GetByEmailParams struct {
	Email string `json:"email"`
}

type GetByEmailRow struct {
	UserID       uuid.UUID `json:"user_id"`
	UserName     string    `json:"user_name"`
	Name         string    `json:"name"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) GetByEmail(ctx context.Context, arg GetByEmailParams) (GetByEmailRow, error) {
	row := q.db.QueryRow(ctx, getByEmail, arg.Email)
	var i GetByEmailRow
	err := row.Scan(
		&i.UserID,
		&i.UserName,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
	)
	return i, err
}

const hardDeleteUser = `-- name: HardDeleteUser :execrows
DELETE FROM users
WHERE user_id = $1
`

type HardDeleteUserParams struct {
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) HardDeleteUser(ctx context.Context, arg HardDeleteUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, hardDeleteUser, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listUsers = `-- name: ListUsers :many
SELECT user_id,user_name, email, name
FROM users
WHERE
    deleted_at IS NULL
    AND (
        $1::TEXT IS NULL OR
        user_name ILIKE '%' || $1 || '%' OR
        email ILIKE '%' || $1 || '%' OR
        name ILIKE '%' || $1 || '%'
    )
ORDER BY
    CASE WHEN $2::text = 'name'  AND $3::text = 'asc'  THEN name       END ASC,
    CASE WHEN $2::text = 'name'  AND $3::text = 'desc' THEN name       END DESC,
    CASE WHEN $2::text = 'email' AND $3::text = 'asc'  THEN email      END ASC,
    CASE WHEN $2::text = 'email' AND $3::text = 'desc' THEN email      END DESC,
    CASE WHEN $2::text = 'created_at' AND $3::text = 'asc' THEN created_at END ASC,
    created_at DESC
LIMIT $5::int
OFFSET $4::int
`

type ListUsersParams struct {
	Search    *string `json:"search"`
	SortBy    string  `json:"sort_by"`
	OrderBy   string  `json:"order_by"`
	OffsetVal int32   `json:"offset_val"`
	LimitVal  int32   `json:"limit_val"`
}

type ListUsersRow struct {
	UserID   uuid.UUID `json:"user_id"`
	UserName string    `json:"user_name"`
	Email    string    `json:"email"`
	Name     string    `json:"name"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers,
		arg.Search,
		arg.SortBy,
		arg.OrderBy,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.UserID,
			&i.UserName,
			&i.Email,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreUser = `-- name: RestoreUser :one
UPDATE users
SET deleted_at = NULL
WHERE user_id = $1
  AND deleted_at IS NOT NULL
RETURNING user_id, user_name, email, name, updated_at
`

type RestoreUserParams struct {
	UserID uuid.UUID `json:"user_id"`
}

type RestoreUserRow struct {
	UserID    uuid.UUID `json:"user_id"`
	UserName  string    `json:"user_name"`
	Email     string    `json:"email"`
	Name      string    `json:"name"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) RestoreUser(ctx context.Context, arg RestoreUserParams) (RestoreUserRow, error) {
	row := q.db.QueryRow(ctx, restoreUser, arg.UserID)
	var i RestoreUserRow
	err := row.Scan(
		&i.UserID,
		&i.UserName,
		&i.Email,
		&i.Name,
		&i.UpdatedAt,
	)
	return i, err
}

const softDeleteUser = `-- name: SoftDeleteUser :execrows
UPDATE users
SET deleted_at = NOW()
WHERE user_id = $1 AND deleted_at IS NULL
`

type SoftDeleteUserParams struct {
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) SoftDeleteUser(ctx context.Context, arg SoftDeleteUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteUser, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUserByID = `-- name: UpdateUserByID :one
UPDATE users
SET 
    name          = COALESCE($1, name),
    email         = COALESCE($2, email),
    user_name     = COALESCE($3, user_name),
    password_hash = COALESCE($4, password_hash),
    updated_at    = NOW()
WHERE user_id = $5 AND deleted_at IS NULL
RETURNING user_id, user_name, name, email, updated_at
`

type UpdateUserByIDParams struct {
	Name         *string   `json:"name"`
	Email        *string   `json:"email"`
	UserName     *string   `json:"user_name"`
	PasswordHash *string   `json:"password_hash"`
	UserID       uuid.UUID `json:"user_id"`
}

type UpdateUserByIDRow struct {
	UserID    uuid.UUID `json:"user_id"`
	UserName  string    `json:"user_name"`
	Name      string    `json:"name"`
	Email     string    `json:"email"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) UpdateUserByID(ctx context.Context, arg UpdateUserByIDParams) (UpdateUserByIDRow, error) {
	row := q.db.QueryRow(ctx, updateUserByID,
		arg.Name,
		arg.Email,
		arg.UserName,
		arg.PasswordHash,
		arg.UserID,
	)
	var i UpdateUserByIDRow
	err := row.Scan(
		&i.UserID,
		&i.UserName,
		&i.Name,
		&i.Email,
		&i.UpdatedAt,
	)
	return i, err
}
