// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users(
    user_name,
    name,
    email,
    password_hash
) VALUES (
    $1, $2, $3, $4
) RETURNING user_id, user_name, name, email, password_hash, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	UserName     string `json:"user_name"`
	Name         string `json:"name"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.UserName,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserName,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const findUserByID = `-- name: FindUserByID :one
SELECT user_id, user_name, name, email, password_hash, created_at, updated_at, deleted_at
FROM users
WHERE user_id = $1 AND deleted_at IS NULL
`

type FindUserByIDParams struct {
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) FindUserByID(ctx context.Context, arg FindUserByIDParams) (User, error) {
	row := q.db.QueryRow(ctx, findUserByID, arg.UserID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserName,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const hardDeleteUser = `-- name: HardDeleteUser :execrows
DELETE FROM users
WHERE user_id = $1
`

type HardDeleteUserParams struct {
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) HardDeleteUser(ctx context.Context, arg HardDeleteUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, hardDeleteUser, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const restoreUser = `-- name: RestoreUser :one
UPDATE users
SET deleted_at = NULL
WHERE user_id = $1
  AND deleted_at IS NOT NULL
RETURNING user_id, user_name, name, email, password_hash, created_at, updated_at, deleted_at
`

type RestoreUserParams struct {
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) RestoreUser(ctx context.Context, arg RestoreUserParams) (User, error) {
	row := q.db.QueryRow(ctx, restoreUser, arg.UserID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserName,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteUser = `-- name: SoftDeleteUser :execrows
UPDATE users
SET deleted_at = NOW()
WHERE user_id = $1 AND deleted_at IS NULL
`

type SoftDeleteUserParams struct {
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) SoftDeleteUser(ctx context.Context, arg SoftDeleteUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteUser, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUserByID = `-- name: UpdateUserByID :one
UPDATE users
SET 
    name          = COALESCE($1, name),
    email         = COALESCE($2, email),
    user_name     = COALESCE($3, user_name),
    password_hash = COALESCE($4, password_hash),
    updated_at    = NOW()
WHERE user_id = $5 AND deleted_at IS NULL
RETURNING user_id, user_name, name, email, password_hash, created_at, updated_at, deleted_at
`

type UpdateUserByIDParams struct {
	Name         *string   `json:"name"`
	Email        *string   `json:"email"`
	UserName     *string   `json:"user_name"`
	PasswordHash *string   `json:"password_hash"`
	UserID       uuid.UUID `json:"user_id"`
}

func (q *Queries) UpdateUserByID(ctx context.Context, arg UpdateUserByIDParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserByID,
		arg.Name,
		arg.Email,
		arg.UserName,
		arg.PasswordHash,
		arg.UserID,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserName,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
